name: "Publish release"
on:
  release:
    types: [published]
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        # @v1.5.1を使用 以下の使用actionをアップデートをする場合はコードがセキュリティ的に問題ないか確認して行ってください。
        # https://github.com/tibdex/github-app-token/commit/7ce9ffdcdeb2ba82b01b51d6584a6a85872336d4
        uses: tibdex/github-app-token@f66c1c31c49c0a4d593a5820a9f1e231af3321ad
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout -b release origin/release
          git rebase origin/v2
          git push origin release
